import {useState} from "react";
import * as UI from "@caret-lab/ui";
import {catalog,defaults,props,reads,settingFields,type Slug} from "./data";
export function Preview({slug}:{slug:Slug}){
 if(slug==="avatar")return <div className="preview-row"><UI.Avatar name="Maya Chen"/><UI.Avatar name="Owen Reed"/></div>;
 if(slug==="tag")return <UI.Tag onRemove={()=>undefined}>billing</UI.Tag>;
 if(slug==="timeline")return <UI.Timeline items={[{title:"Submitted",detail:"Claim CLM-1042",time:"09:12"},{title:"Approved",detail:"By Maya Chen",time:"11:48"},{title:"Paid",detail:"ACH transfer",time:"Today"}]}/>;
 if(slug==="file-upload")return <UI.FileUpload label="Attach receipt" accept="image/*,.pdf"/>;
 if(slug==="currency-field")return <UI.CurrencyField label="Amount"/>;
 if(slug==="search")return <UI.Search label="Search tickets"/>;
 if(slug==="select")return <UI.Select label="Priority" options={[{value:"high",label:"High"},{value:"normal",label:"Normal"},{value:"low",label:"Low"}]}/>;
 if(slug==="combobox")return <UI.Combobox label="Assignee" options={["Maya Chen","Owen Reed","Ari Patel"]}/>;
 if(slug==="tabs")return <UI.Tabs items={[{value:"mine",label:"Mine",content:"12 assigned tickets"},{value:"unassigned",label:"Unassigned",content:"4 tickets need an owner"},{value:"all",label:"All",content:"36 total tickets"}]}/>;
 if(slug==="table")return <UI.Table columns={["ID","Title","Status","Assignee"]} rows={[["TK-1042","Refund request",<UI.Badge>Open</UI.Badge>,"Maya Chen"],["TK-1041","Invoice mismatch",<UI.Badge intent="negative">Blocked</UI.Badge>,"Owen Reed"]]}/>;
 if(slug==="badge")return <div className="preview-row"><UI.Badge intent="positive">Paid</UI.Badge><UI.Badge intent="negative">Overdue</UI.Badge><UI.Badge>Draft</UI.Badge></div>;
 if(slug==="drawer")return <UI.Drawer trigger="Open invoice INV-2048" title="Invoice INV-2048"><p>Northstar Studio · USD 1,250.00</p><UI.Timeline items={[{title:"Sent",time:"Sep 18"},{title:"Viewed",time:"Sep 19"}]}/></UI.Drawer>;
 if(slug==="textarea")return <UI.Textarea label="Reply" placeholder="Write a reply…"/>;
 if(slug==="menu")return <UI.Menu label="Ticket actions" items={[{label:"Assign"},{label:"Change status"},{label:"Close"}]}/>;
 if(slug==="dialog")return <UI.Dialog trigger="Close ticket" title="Close this ticket?" confirmLabel="Close ticket"><p>This moves it out of the active queue.</p></UI.Dialog>;
 if(slug==="toast")return <UI.Toast trigger="Save changes" message="Changes saved"/>;
 if(slug==="date-field")return <UI.DateField label="Due date" defaultValue="2026-10-15"/>;
 if(slug==="quantity")return <UI.Quantity label="Line-item quantity"/>;
 if(slug==="input")return <UI.Input label="Line description" placeholder="Design services"/>;
 if(slug==="alert")return <UI.Alert title="Receipt required">Attach a receipt before submitting this claim.</UI.Alert>;
 if(slug==="link")return <UI.Link href="#client">Open Northstar Studio</UI.Link>;
 if(slug==="button")return <div className="preview-row"><UI.Button>Confirm</UI.Button><UI.Button intent="negative">Delete</UI.Button><UI.Button variant="secondary">Cancel</UI.Button><UI.Button disabled>Save</UI.Button></div>;
 return <div className="preview-stack"><UI.Checkbox label="Select claim"/><UI.Checkbox label="Selected claim" defaultChecked/><UI.Checkbox label="Unavailable claim" disabled/></div>;
}
export function SettingsForm({fields,onChange}:{fields:string[];onChange:(s:UI.ThemeSettings)=>void}){const [colors,setColors]=useState<Record<string,string>>(()=>Object.fromEntries(fields.map(f=>[f,defaults[f as keyof typeof defaults]])));const [fontFamily,setFont]=useState<"sans"|"serif"|"mono">("sans");const [bodySize,setSize]=useState<"sm"|"md"|"lg">("md");const [radius,setRadius]=useState<"none"|"sm"|"md">("sm");function emit(next=colors,f=fontFamily,b=bodySize,r=radius){onChange({colors:next,typography:{fontFamily:f,bodySize:b},radius:r})}return <div className="settings-form"><div className="settings-colors">{fields.map(field=><label className="setting-control" key={field}><span>{field}</span><span className="color-field"><input type="color" value={/^#[0-9a-fA-F]{6}$/.test(colors[field]??"")?colors[field]:"#000000"} onChange={e=>{const n={...colors,[field]:e.target.value};setColors(n);emit(n)}}/><input aria-label={`${field} hex value`} value={colors[field]??""} pattern="#[0-9a-fA-F]{3}|#[0-9a-fA-F]{6}" onChange={e=>{const n={...colors,[field]:e.target.value};setColors(n);emit(n)}}/></span></label>)}</div><div className="settings-options"><label className="setting-control"><span>font family</span><select value={fontFamily} onChange={e=>{const v=e.target.value as typeof fontFamily;setFont(v);emit(colors,v)}}><option>sans</option><option>serif</option><option>mono</option></select></label><label className="setting-control"><span>body size</span><select value={bodySize} onChange={e=>{const v=e.target.value as typeof bodySize;setSize(v);emit(colors,fontFamily,v)}}><option>sm</option><option>md</option><option>lg</option></select></label><label className="setting-control"><span>radius</span><select value={radius} onChange={e=>{const v=e.target.value as typeof radius;setRadius(v);emit(colors,fontFamily,bodySize,v)}}><option>none</option><option>sm</option><option>md</option></select></label></div></div>}
export function ComponentPage({slug}:{slug:Slug}){const item=catalog.find(i=>i.slug===slug);const [settings,setSettings]=useState<UI.ThemeSettings>({});if(!item)return null;return <main className="page"><div className="page-kicker">Catalog / {String(catalog.findIndex(x=>x.slug===slug)+1).padStart(2,"0")}</div><div className="page-heading"><div><h1>{item.name}</h1><p>{item.desc}.</p></div><code>{item.imp}</code></div><section><div className="section-label"><h2>Preview</h2><span>Isolated ThemeScope</span></div><UI.ThemeScope settings={settings} className="preview-frame"><Preview slug={slug}/></UI.ThemeScope></section><section><div className="section-label"><h2>Settings for this preview</h2><span>Frame only</span></div><SettingsForm fields={settingFields[slug]} onChange={setSettings}/></section><section className="detail-grid"><div><h2>Import</h2><pre><code>{`import '@caret-lab/ui/tokens.css';\n${item.imp};\nimport { ThemeScope, type ThemeSettings } from '@caret-lab/ui/settings';`}</code></pre></div><div><h2>Props</h2><ul>{props[slug].map(x=><li key={x}><code>{x}</code></li>)}</ul></div></section><section><h2>Reads</h2><div className="token-list">{reads[slug].map(x=><code key={x}>{x}</code>)}</div></section></main>}