export type Slug="avatar"|"tag"|"timeline"|"file-upload"|"currency-field"|"search"|"select"|"combobox"|"tabs"|"table"|"badge"|"drawer"|"textarea"|"menu"|"dialog"|"toast"|"date-field"|"quantity"|"input"|"alert"|"link"|"checkbox"|"button";
type Item={slug:Slug;name:string;desc:string;imp:string};
const entries:[Slug,string,string][]=[
 ["avatar","Avatar","Identifies an owner, requester, or approver"],["tag","Tag","A removable label for work and categories"],["timeline","Timeline","An ordered history of activity and decisions"],["file-upload","File Upload","Attaches screenshots, receipts, and invoice files"],["currency-field","Currency Field","Captures a monetary amount with its currency"],["search","Search","Finds projects, tickets, clients, and people"],["select","Select","Chooses one value from a known list"],["combobox","Combobox","Searches and chooses from a longer list"],["tabs","Tabs","Switches between related views"],["table","Table","Presents structured records for scanning"],["badge","Badge","Shows a compact status"],["drawer","Drawer","Opens record detail without leaving the list"],["textarea","Textarea","Captures descriptions, notes, and replies"],["menu","Menu","Groups contextual actions"],["dialog","Dialog","Requests confirmation for a consequential action"],["toast","Toast","Confirms a completed action"],["date-field","Date Field","Captures an issued, due, paid, or expense date"],["quantity","Quantity","Captures a count rather than money"],["input","Input","Captures a short line of text"],["alert","Alert","Communicates a warning that needs attention"],["link","Link","Opens a related record or source"],["checkbox","Checkbox","Selects one or more records"],["button","Button","Confirms, cancels, or submits an action"]];
const pascal=(slug:Slug)=>slug.split("-").map(x=>x[0]?.toUpperCase()+x.slice(1)).join("");
export const catalog:Item[]=entries.map(([slug,name,desc])=>({slug,name,desc,imp:`import { ${pascal(slug)} } from '@caret-lab/ui'`}));
const common=(name:string)=>[`--${name}-font-family`,`--${name}-font-size`,`--${name}-radius`,`--${name}-color`,`--${name}-background`,`--${name}-border-color`];
export const reads=Object.fromEntries(entries.map(([slug])=>[slug,common(slug)])) as Record<Slug,string[]>;
reads.button=["--button-font-family","--button-font-size","--button-padding-block","--button-padding-inline","--button-radius","--button-color-on-fill","--button-positive-background-active","--button-positive-background-hover","--button-positive-background-disabled","--button-negative-background-active","--button-negative-background-hover","--button-negative-background-disabled","--button-background-secondary","--button-color-secondary","--button-border-color-secondary"];
export const props:Record<Slug,string[]>={
 avatar:["name: string — required","src?: string","size?: 'sm' | 'md' | 'lg'"],tag:["children: tag label","onRemove?: () => void"],timeline:["items: { title: string; detail?: string; time?: string }[]"],"file-upload":["label: string — required","accept?: string","onFiles?: (files: File[]) => void"],"currency-field":["label: string — required","currency?: string — default USD","value?: number","onChange?: (value: number) => void"],search:["label: string — required","native search input attributes"],select:["label: string — required","options: { value: string; label: string }[]"],combobox:["label: string — required","options: string[]"],tabs:["items: { value: string; label: string; content: ReactNode }[]","defaultValue?: string"],table:["columns: string[]","rows: ReactNode[][]"],badge:["intent?: 'positive' | 'negative' | 'neutral'","children: badge text"],drawer:["trigger: ReactNode","title: string","children: drawer content"],textarea:["label: string — required","rows?: number — default 3","native textarea attributes"],menu:["label: string","items: { label: string; onSelect?: () => void }[]"],dialog:["trigger: ReactNode","title: string","children: dialog content","confirmLabel?: string","defaultOpen?: boolean","onConfirm?: () => void"],toast:["trigger: ReactNode","message: string"],"date-field":["label: string — required","native date input attributes"],quantity:["label: string — required","min?: number","max?: number","value?: number"],input:["label: string — required","native text input attributes"],alert:["title: string — required","children?: alert detail"],link:["href: string — required","children: link text"],checkbox:["label: string — required","defaultChecked?: boolean","disabled?: boolean"],button:["intent?: 'positive' | 'negative' — default positive","variant?: 'primary' | 'secondary' — default primary","disabled?: boolean","children: button label"]};
const colorFields=["positiveActive","positiveHover","positiveDisabled","negativeActive","negativeHover","negativeDisabled","textDefault","textOnAction","surfaceRaised","surfaceBorder"];
export const settingFields=Object.fromEntries(entries.map(([slug])=>[slug,colorFields])) as Record<Slug,string[]>;
export const defaults={positiveActive:"#176b55",positiveHover:"#105744",positiveDisabled:"#a9c7bd",negativeActive:"#a13d4a",negativeHover:"#842f3b",negativeDisabled:"#d6aeb4",textDefault:"#17242b",textOnAction:"#ffffff",surfaceRaised:"#ffffff",surfaceBorder:"#b8c4c8"};