/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as InstallRouteImport } from './routes/install'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogAlertRouteImport } from './routes/catalog.alert'
import { Route as CatalogAvatarRouteImport } from './routes/catalog.avatar'
import { Route as CatalogBadgeRouteImport } from './routes/catalog.badge'
import { Route as CatalogButtonRouteImport } from './routes/catalog.button'
import { Route as CatalogCheckboxRouteImport } from './routes/catalog.checkbox'
import { Route as CatalogComboboxRouteImport } from './routes/catalog.combobox'
import { Route as CatalogCurrencyFieldRouteImport } from './routes/catalog.currency-field'
import { Route as CatalogDateFieldRouteImport } from './routes/catalog.date-field'
import { Route as CatalogDialogRouteImport } from './routes/catalog.dialog'
import { Route as CatalogDrawerRouteImport } from './routes/catalog.drawer'
import { Route as CatalogFileUploadRouteImport } from './routes/catalog.file-upload'
import { Route as CatalogInputRouteImport } from './routes/catalog.input'
import { Route as CatalogLinkRouteImport } from './routes/catalog.link'
import { Route as CatalogMenuRouteImport } from './routes/catalog.menu'
import { Route as CatalogQuantityRouteImport } from './routes/catalog.quantity'
import { Route as CatalogSearchRouteImport } from './routes/catalog.search'
import { Route as CatalogSelectRouteImport } from './routes/catalog.select'
import { Route as CatalogSettingsRouteImport } from './routes/catalog.settings'
import { Route as CatalogTableRouteImport } from './routes/catalog.table'
import { Route as CatalogTabsRouteImport } from './routes/catalog.tabs'
import { Route as CatalogTagRouteImport } from './routes/catalog.tag'
import { Route as CatalogTextareaRouteImport } from './routes/catalog.textarea'
import { Route as CatalogTimelineRouteImport } from './routes/catalog.timeline'
import { Route as CatalogToastRouteImport } from './routes/catalog.toast'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogAlertRoute = CatalogAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogAvatarRoute = CatalogAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogBadgeRoute = CatalogBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogButtonRoute = CatalogButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogCheckboxRoute = CatalogCheckboxRouteImport.update({
  id: '/checkbox',
  path: '/checkbox',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogComboboxRoute = CatalogComboboxRouteImport.update({
  id: '/combobox',
  path: '/combobox',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogCurrencyFieldRoute = CatalogCurrencyFieldRouteImport.update({
  id: '/currency-field',
  path: '/currency-field',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogDateFieldRoute = CatalogDateFieldRouteImport.update({
  id: '/date-field',
  path: '/date-field',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogDialogRoute = CatalogDialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogDrawerRoute = CatalogDrawerRouteImport.update({
  id: '/drawer',
  path: '/drawer',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogFileUploadRoute = CatalogFileUploadRouteImport.update({
  id: '/file-upload',
  path: '/file-upload',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogInputRoute = CatalogInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogLinkRoute = CatalogLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogMenuRoute = CatalogMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogQuantityRoute = CatalogQuantityRouteImport.update({
  id: '/quantity',
  path: '/quantity',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogSearchRoute = CatalogSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogSelectRoute = CatalogSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogSettingsRoute = CatalogSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogTableRoute = CatalogTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogTabsRoute = CatalogTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogTagRoute = CatalogTagRouteImport.update({
  id: '/tag',
  path: '/tag',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogTextareaRoute = CatalogTextareaRouteImport.update({
  id: '/textarea',
  path: '/textarea',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogTimelineRoute = CatalogTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogToastRoute = CatalogToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => CatalogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/install': typeof InstallRoute
  '/showcase': typeof ShowcaseRoute
  '/catalog/alert': typeof CatalogAlertRoute
  '/catalog/avatar': typeof CatalogAvatarRoute
  '/catalog/badge': typeof CatalogBadgeRoute
  '/catalog/button': typeof CatalogButtonRoute
  '/catalog/checkbox': typeof CatalogCheckboxRoute
  '/catalog/combobox': typeof CatalogComboboxRoute
  '/catalog/currency-field': typeof CatalogCurrencyFieldRoute
  '/catalog/date-field': typeof CatalogDateFieldRoute
  '/catalog/dialog': typeof CatalogDialogRoute
  '/catalog/drawer': typeof CatalogDrawerRoute
  '/catalog/file-upload': typeof CatalogFileUploadRoute
  '/catalog/input': typeof CatalogInputRoute
  '/catalog/link': typeof CatalogLinkRoute
  '/catalog/menu': typeof CatalogMenuRoute
  '/catalog/quantity': typeof CatalogQuantityRoute
  '/catalog/search': typeof CatalogSearchRoute
  '/catalog/select': typeof CatalogSelectRoute
  '/catalog/settings': typeof CatalogSettingsRoute
  '/catalog/table': typeof CatalogTableRoute
  '/catalog/tabs': typeof CatalogTabsRoute
  '/catalog/tag': typeof CatalogTagRoute
  '/catalog/textarea': typeof CatalogTextareaRoute
  '/catalog/timeline': typeof CatalogTimelineRoute
  '/catalog/toast': typeof CatalogToastRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/showcase': typeof ShowcaseRoute
  '/catalog/alert': typeof CatalogAlertRoute
  '/catalog/avatar': typeof CatalogAvatarRoute
  '/catalog/badge': typeof CatalogBadgeRoute
  '/catalog/button': typeof CatalogButtonRoute
  '/catalog/checkbox': typeof CatalogCheckboxRoute
  '/catalog/combobox': typeof CatalogComboboxRoute
  '/catalog/currency-field': typeof CatalogCurrencyFieldRoute
  '/catalog/date-field': typeof CatalogDateFieldRoute
  '/catalog/dialog': typeof CatalogDialogRoute
  '/catalog/drawer': typeof CatalogDrawerRoute
  '/catalog/file-upload': typeof CatalogFileUploadRoute
  '/catalog/input': typeof CatalogInputRoute
  '/catalog/link': typeof CatalogLinkRoute
  '/catalog/menu': typeof CatalogMenuRoute
  '/catalog/quantity': typeof CatalogQuantityRoute
  '/catalog/search': typeof CatalogSearchRoute
  '/catalog/select': typeof CatalogSelectRoute
  '/catalog/settings': typeof CatalogSettingsRoute
  '/catalog/table': typeof CatalogTableRoute
  '/catalog/tabs': typeof CatalogTabsRoute
  '/catalog/tag': typeof CatalogTagRoute
  '/catalog/textarea': typeof CatalogTextareaRoute
  '/catalog/timeline': typeof CatalogTimelineRoute
  '/catalog/toast': typeof CatalogToastRoute
  '/catalog': typeof CatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/install': typeof InstallRoute
  '/showcase': typeof ShowcaseRoute
  '/catalog/alert': typeof CatalogAlertRoute
  '/catalog/avatar': typeof CatalogAvatarRoute
  '/catalog/badge': typeof CatalogBadgeRoute
  '/catalog/button': typeof CatalogButtonRoute
  '/catalog/checkbox': typeof CatalogCheckboxRoute
  '/catalog/combobox': typeof CatalogComboboxRoute
  '/catalog/currency-field': typeof CatalogCurrencyFieldRoute
  '/catalog/date-field': typeof CatalogDateFieldRoute
  '/catalog/dialog': typeof CatalogDialogRoute
  '/catalog/drawer': typeof CatalogDrawerRoute
  '/catalog/file-upload': typeof CatalogFileUploadRoute
  '/catalog/input': typeof CatalogInputRoute
  '/catalog/link': typeof CatalogLinkRoute
  '/catalog/menu': typeof CatalogMenuRoute
  '/catalog/quantity': typeof CatalogQuantityRoute
  '/catalog/search': typeof CatalogSearchRoute
  '/catalog/select': typeof CatalogSelectRoute
  '/catalog/settings': typeof CatalogSettingsRoute
  '/catalog/table': typeof CatalogTableRoute
  '/catalog/tabs': typeof CatalogTabsRoute
  '/catalog/tag': typeof CatalogTagRoute
  '/catalog/textarea': typeof CatalogTextareaRoute
  '/catalog/timeline': typeof CatalogTimelineRoute
  '/catalog/toast': typeof CatalogToastRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/install'
    | '/showcase'
    | '/catalog/alert'
    | '/catalog/avatar'
    | '/catalog/badge'
    | '/catalog/button'
    | '/catalog/checkbox'
    | '/catalog/combobox'
    | '/catalog/currency-field'
    | '/catalog/date-field'
    | '/catalog/dialog'
    | '/catalog/drawer'
    | '/catalog/file-upload'
    | '/catalog/input'
    | '/catalog/link'
    | '/catalog/menu'
    | '/catalog/quantity'
    | '/catalog/search'
    | '/catalog/select'
    | '/catalog/settings'
    | '/catalog/table'
    | '/catalog/tabs'
    | '/catalog/tag'
    | '/catalog/textarea'
    | '/catalog/timeline'
    | '/catalog/toast'
    | '/catalog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/install'
    | '/showcase'
    | '/catalog/alert'
    | '/catalog/avatar'
    | '/catalog/badge'
    | '/catalog/button'
    | '/catalog/checkbox'
    | '/catalog/combobox'
    | '/catalog/currency-field'
    | '/catalog/date-field'
    | '/catalog/dialog'
    | '/catalog/drawer'
    | '/catalog/file-upload'
    | '/catalog/input'
    | '/catalog/link'
    | '/catalog/menu'
    | '/catalog/quantity'
    | '/catalog/search'
    | '/catalog/select'
    | '/catalog/settings'
    | '/catalog/table'
    | '/catalog/tabs'
    | '/catalog/tag'
    | '/catalog/textarea'
    | '/catalog/timeline'
    | '/catalog/toast'
    | '/catalog'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/install'
    | '/showcase'
    | '/catalog/alert'
    | '/catalog/avatar'
    | '/catalog/badge'
    | '/catalog/button'
    | '/catalog/checkbox'
    | '/catalog/combobox'
    | '/catalog/currency-field'
    | '/catalog/date-field'
    | '/catalog/dialog'
    | '/catalog/drawer'
    | '/catalog/file-upload'
    | '/catalog/input'
    | '/catalog/link'
    | '/catalog/menu'
    | '/catalog/quantity'
    | '/catalog/search'
    | '/catalog/select'
    | '/catalog/settings'
    | '/catalog/table'
    | '/catalog/tabs'
    | '/catalog/tag'
    | '/catalog/textarea'
    | '/catalog/timeline'
    | '/catalog/toast'
    | '/catalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  InstallRoute: typeof InstallRoute
  ShowcaseRoute: typeof ShowcaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/alert': {
      id: '/catalog/alert'
      path: '/alert'
      fullPath: '/catalog/alert'
      preLoaderRoute: typeof CatalogAlertRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/avatar': {
      id: '/catalog/avatar'
      path: '/avatar'
      fullPath: '/catalog/avatar'
      preLoaderRoute: typeof CatalogAvatarRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/badge': {
      id: '/catalog/badge'
      path: '/badge'
      fullPath: '/catalog/badge'
      preLoaderRoute: typeof CatalogBadgeRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/button': {
      id: '/catalog/button'
      path: '/button'
      fullPath: '/catalog/button'
      preLoaderRoute: typeof CatalogButtonRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/checkbox': {
      id: '/catalog/checkbox'
      path: '/checkbox'
      fullPath: '/catalog/checkbox'
      preLoaderRoute: typeof CatalogCheckboxRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/combobox': {
      id: '/catalog/combobox'
      path: '/combobox'
      fullPath: '/catalog/combobox'
      preLoaderRoute: typeof CatalogComboboxRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/currency-field': {
      id: '/catalog/currency-field'
      path: '/currency-field'
      fullPath: '/catalog/currency-field'
      preLoaderRoute: typeof CatalogCurrencyFieldRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/date-field': {
      id: '/catalog/date-field'
      path: '/date-field'
      fullPath: '/catalog/date-field'
      preLoaderRoute: typeof CatalogDateFieldRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/dialog': {
      id: '/catalog/dialog'
      path: '/dialog'
      fullPath: '/catalog/dialog'
      preLoaderRoute: typeof CatalogDialogRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/drawer': {
      id: '/catalog/drawer'
      path: '/drawer'
      fullPath: '/catalog/drawer'
      preLoaderRoute: typeof CatalogDrawerRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/file-upload': {
      id: '/catalog/file-upload'
      path: '/file-upload'
      fullPath: '/catalog/file-upload'
      preLoaderRoute: typeof CatalogFileUploadRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/input': {
      id: '/catalog/input'
      path: '/input'
      fullPath: '/catalog/input'
      preLoaderRoute: typeof CatalogInputRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/link': {
      id: '/catalog/link'
      path: '/link'
      fullPath: '/catalog/link'
      preLoaderRoute: typeof CatalogLinkRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/menu': {
      id: '/catalog/menu'
      path: '/menu'
      fullPath: '/catalog/menu'
      preLoaderRoute: typeof CatalogMenuRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/quantity': {
      id: '/catalog/quantity'
      path: '/quantity'
      fullPath: '/catalog/quantity'
      preLoaderRoute: typeof CatalogQuantityRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/search': {
      id: '/catalog/search'
      path: '/search'
      fullPath: '/catalog/search'
      preLoaderRoute: typeof CatalogSearchRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/select': {
      id: '/catalog/select'
      path: '/select'
      fullPath: '/catalog/select'
      preLoaderRoute: typeof CatalogSelectRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/settings': {
      id: '/catalog/settings'
      path: '/settings'
      fullPath: '/catalog/settings'
      preLoaderRoute: typeof CatalogSettingsRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/table': {
      id: '/catalog/table'
      path: '/table'
      fullPath: '/catalog/table'
      preLoaderRoute: typeof CatalogTableRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/tabs': {
      id: '/catalog/tabs'
      path: '/tabs'
      fullPath: '/catalog/tabs'
      preLoaderRoute: typeof CatalogTabsRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/tag': {
      id: '/catalog/tag'
      path: '/tag'
      fullPath: '/catalog/tag'
      preLoaderRoute: typeof CatalogTagRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/textarea': {
      id: '/catalog/textarea'
      path: '/textarea'
      fullPath: '/catalog/textarea'
      preLoaderRoute: typeof CatalogTextareaRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/timeline': {
      id: '/catalog/timeline'
      path: '/timeline'
      fullPath: '/catalog/timeline'
      preLoaderRoute: typeof CatalogTimelineRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/catalog/toast': {
      id: '/catalog/toast'
      path: '/toast'
      fullPath: '/catalog/toast'
      preLoaderRoute: typeof CatalogToastRouteImport
      parentRoute: typeof CatalogRoute
    }
  }
}

interface CatalogRouteChildren {
  CatalogAlertRoute: typeof CatalogAlertRoute
  CatalogAvatarRoute: typeof CatalogAvatarRoute
  CatalogBadgeRoute: typeof CatalogBadgeRoute
  CatalogButtonRoute: typeof CatalogButtonRoute
  CatalogCheckboxRoute: typeof CatalogCheckboxRoute
  CatalogComboboxRoute: typeof CatalogComboboxRoute
  CatalogCurrencyFieldRoute: typeof CatalogCurrencyFieldRoute
  CatalogDateFieldRoute: typeof CatalogDateFieldRoute
  CatalogDialogRoute: typeof CatalogDialogRoute
  CatalogDrawerRoute: typeof CatalogDrawerRoute
  CatalogFileUploadRoute: typeof CatalogFileUploadRoute
  CatalogInputRoute: typeof CatalogInputRoute
  CatalogLinkRoute: typeof CatalogLinkRoute
  CatalogMenuRoute: typeof CatalogMenuRoute
  CatalogQuantityRoute: typeof CatalogQuantityRoute
  CatalogSearchRoute: typeof CatalogSearchRoute
  CatalogSelectRoute: typeof CatalogSelectRoute
  CatalogSettingsRoute: typeof CatalogSettingsRoute
  CatalogTableRoute: typeof CatalogTableRoute
  CatalogTabsRoute: typeof CatalogTabsRoute
  CatalogTagRoute: typeof CatalogTagRoute
  CatalogTextareaRoute: typeof CatalogTextareaRoute
  CatalogTimelineRoute: typeof CatalogTimelineRoute
  CatalogToastRoute: typeof CatalogToastRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogAlertRoute: CatalogAlertRoute,
  CatalogAvatarRoute: CatalogAvatarRoute,
  CatalogBadgeRoute: CatalogBadgeRoute,
  CatalogButtonRoute: CatalogButtonRoute,
  CatalogCheckboxRoute: CatalogCheckboxRoute,
  CatalogComboboxRoute: CatalogComboboxRoute,
  CatalogCurrencyFieldRoute: CatalogCurrencyFieldRoute,
  CatalogDateFieldRoute: CatalogDateFieldRoute,
  CatalogDialogRoute: CatalogDialogRoute,
  CatalogDrawerRoute: CatalogDrawerRoute,
  CatalogFileUploadRoute: CatalogFileUploadRoute,
  CatalogInputRoute: CatalogInputRoute,
  CatalogLinkRoute: CatalogLinkRoute,
  CatalogMenuRoute: CatalogMenuRoute,
  CatalogQuantityRoute: CatalogQuantityRoute,
  CatalogSearchRoute: CatalogSearchRoute,
  CatalogSelectRoute: CatalogSelectRoute,
  CatalogSettingsRoute: CatalogSettingsRoute,
  CatalogTableRoute: CatalogTableRoute,
  CatalogTabsRoute: CatalogTabsRoute,
  CatalogTagRoute: CatalogTagRoute,
  CatalogTextareaRoute: CatalogTextareaRoute,
  CatalogTimelineRoute: CatalogTimelineRoute,
  CatalogToastRoute: CatalogToastRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRouteWithChildren,
  InstallRoute: InstallRoute,
  ShowcaseRoute: ShowcaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
