import {useState,type CSSProperties,type InputHTMLAttributes,type ReactNode,type TextareaHTMLAttributes} from "react";
import "./tokens.css";
export type ThemeSettings={colors?:{positiveActive?:string;positiveHover?:string;positiveDisabled?:string;negativeActive?:string;negativeHover?:string;negativeDisabled?:string;textDefault?:string;textOnAction?:string;surfaceRaised?:string;surfaceBorder?:string};typography?:{fontFamily?:"sans"|"serif"|"mono";bodySize?:"sm"|"md"|"lg"};radius?:"none"|"sm"|"md"};
const names=["avatar","tag","timeline","file-upload","currency-field","search","select","combobox","tabs","table","badge","drawer","textarea","menu","dialog","toast","date-field","quantity","input","alert","link","checkbox"];
const colorMap={positiveActive:["--color-action-positive-active","--badge-positive-background"],positiveHover:["--color-action-positive-hover"],positiveDisabled:["--color-action-positive-disabled"],negativeActive:["--color-action-negative-active","--badge-negative-background"],negativeHover:["--color-action-negative-hover"],negativeDisabled:["--color-action-negative-disabled"],textDefault:["--color-text-default","--badge-neutral-color","--link-color"],textOnAction:["--color-text-on-action","--badge-positive-color","--badge-negative-color"],surfaceRaised:["--color-surface-raised","--badge-neutral-background"],surfaceBorder:["--color-surface-border","--badge-neutral-border-color"]} as const;
const hex=/^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;
export function ThemeScope({settings={},children,className=""}:{settings?:ThemeSettings;children:ReactNode;className?:string}){const style:Record<string,string>={};Object.entries(settings.colors??{}).forEach(([k,v])=>{if(v&&hex.test(v)){colorMap[k as keyof typeof colorMap]?.forEach(x=>style[x]=v);names.forEach(n=>{if(k==="textDefault")style[`--${n}-color`]=v;if(k==="surfaceRaised")style[`--${n}-background`]=v;if(k==="surfaceBorder")style[`--${n}-border-color`]=v})}});if(settings.typography?.fontFamily){const v={sans:"ui-sans-serif, system-ui, sans-serif",serif:"Georgia, serif",mono:"ui-monospace, monospace"}[settings.typography.fontFamily];style["--font-family-sans"]=v;names.forEach(n=>style[`--${n}-font-family`]=v)}if(settings.typography?.bodySize){const v={sm:"14px",md:"16px",lg:"20px"}[settings.typography.bodySize];style["--font-size-md"]=v;names.forEach(n=>style[`--${n}-font-size`]=v)}if(settings.radius){const v={none:"0",sm:"6px",md:"10px"}[settings.radius];style["--radius-sm"]=v;names.forEach(n=>style[`--${n}-radius`]=v)}return <div className={`showcase-scope ${className}`} style={style as CSSProperties}>{children}</div>}
export function Avatar({name,src}:{name:string;src?:string}){return <span className="sc-avatar">{src?<img src={src} alt={name}/>:name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span>}
export function Tag({children,onRemove}:{children:ReactNode;onRemove?:()=>void}){return <span className="sc-tag">{children}{onRemove&&<button aria-label="Remove tag" onClick={onRemove}>×</button>}</span>}
export function Timeline({items}:{items:{title:string;detail?:string;time?:string}[]}){return <ol className="sc-timeline">{items.map((x,i)=><li key={`${x.title}-${i}`}><i/><div><strong>{x.title}</strong>{x.detail&&<span>{x.detail}</span>}</div>{x.time&&<time>{x.time}</time>}</li>)}</ol>}
export function FileUpload({label,accept,onFiles}:{label:string;accept?:string;onFiles?:(f:File[])=>void}){const [name,setName]=useState("");return <label className="sc-upload"><strong>{label}</strong><span>{name||"Choose a file"}</span><input type="file" accept={accept} onChange={e=>{const f=Array.from(e.target.files??[]);setName(f[0]?.name??"");onFiles?.(f)}}/></label>}
export function CurrencyField({label,currency="USD"}:{label:string;currency?:string}){return <label className="sc-field sc-money"><span>{label}</span><span><select aria-label="Currency" defaultValue={currency}><option>USD</option><option>EUR</option><option>GBP</option></select><input type="number" inputMode="decimal" defaultValue="1250.00"/></span></label>}
export function Search({label,...p}:{label:string}&InputHTMLAttributes<HTMLInputElement>){return <label className="sc-field"><span>{label}</span><input type="search" placeholder="Search…" {...p}/></label>}
export function Select({label,options}:{label:string;options:{value:string;label:string}[]}){return <label className="sc-field"><span>{label}</span><select>{options.map(x=><option value={x.value} key={x.value}>{x.label}</option>)}</select></label>}
export function Combobox({label,options}:{label:string;options:string[]}){const id=`combo-${label.replace(/\s/g,"-")}`;return <label className="sc-field"><span>{label}</span><input list={id} placeholder="Type to search…"/><datalist id={id}>{options.map(x=><option value={x} key={x}/>)}</datalist></label>}
export function Tabs({items}:{items:{value:string;label:string;content:ReactNode}[]}){const [active,setActive]=useState(items[0]?.value??"");return <div className="sc-tabs"><div role="tablist">{items.map(x=><button role="tab" aria-selected={active===x.value} onClick={()=>setActive(x.value)} key={x.value}>{x.label}</button>)}</div><div role="tabpanel">{items.find(x=>x.value===active)?.content}</div></div>}
export function Table({columns,rows}:{columns:string[];rows:ReactNode[][]}){return <div className="sc-table-wrap"><table className="sc-table"><thead><tr>{columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
export function Badge({intent="neutral",children}:{intent?:"positive"|"negative"|"neutral";children:ReactNode}){return <span className={`sc-badge ${intent}`}>{children}</span>}
export function Drawer({trigger,title,children}:{trigger:ReactNode;title:string;children:ReactNode}){const [open,setOpen]=useState(false);return <><button className="sc-trigger" onClick={()=>setOpen(true)}>{trigger}</button>{open&&<div className="sc-overlay" onClick={()=>setOpen(false)}><aside className="sc-drawer" onClick={e=>e.stopPropagation()}><button aria-label="Close" onClick={()=>setOpen(false)}>×</button><h3>{title}</h3>{children}</aside></div>}</>}
export function Input({label,...p}:{label:string}&InputHTMLAttributes<HTMLInputElement>){return <label className="sc-field"><span>{label}</span><input type="text" {...p}/></label>}
export function Textarea({label,rows=3,...p}:{label:string}&TextareaHTMLAttributes<HTMLTextAreaElement>){return <label className="sc-field sc-textarea"><span>{label}</span><textarea rows={rows} {...p}/></label>}
export function Menu({label,items}:{label:string;items:{label:string;onSelect?:()=>void}[]}){const [open,setOpen]=useState(false);return <div className="sc-menu"><button className="sc-trigger" onClick={()=>setOpen(!open)}>{label} ···</button>{open&&<div>{items.map(x=><button key={x.label} onClick={()=>{x.onSelect?.();setOpen(false)}}>{x.label}</button>)}</div>}</div>}
export function Dialog({trigger,title,children,confirmLabel="Confirm"}:{trigger:ReactNode;title:string;children:ReactNode;confirmLabel?:string}){const [open,setOpen]=useState(false);return <><button className="sc-trigger" onClick={()=>setOpen(true)}>{trigger}</button>{open&&<div className="sc-overlay"><div className="sc-dialog" role="dialog" aria-modal><h3>{title}</h3><div>{children}</div><footer><button onClick={()=>setOpen(false)}>Cancel</button><button onClick={()=>setOpen(false)}>{confirmLabel}</button></footer></div></div>}</>}
export function Toast({trigger,message}:{trigger:ReactNode;message:string}){const [shown,setShown]=useState(false);return <div className="sc-toast-demo"><button className="sc-trigger" onClick={()=>setShown(true)}>{trigger}</button>{shown&&<div className="sc-toast" role="status">{message}<button aria-label="Dismiss" onClick={()=>setShown(false)}>×</button></div>}</div>}
export function DateField({label,...p}:{label:string}&InputHTMLAttributes<HTMLInputElement>){return <label className="sc-field"><span>{label}</span><input type="date" {...p}/></label>}
export function Quantity({label,min=0,max=99}:{label:string;min?:number;max?:number}){const [value,setValue]=useState(1);return <div className="sc-quantity"><span>{label}</span><div><button aria-label="Decrease" onClick={()=>setValue(v=>Math.max(min,v-1))}>−</button><output>{value}</output><button aria-label="Increase" onClick={()=>setValue(v=>Math.min(max,v+1))}>+</button></div></div>}
export function Alert({title,children}:{title:string;children?:ReactNode}){return <div className="sc-alert" role="alert"><strong>{title}</strong>{children&&<span>{children}</span>}</div>}
export function Link({href,children}:{href:string;children:ReactNode}){return <a className="sc-link" href={href} onClick={e=>e.preventDefault()}>{children}</a>}
export function Checkbox({label,...p}:{label:string}&InputHTMLAttributes<HTMLInputElement>){return <label className="sc-check"><input type="checkbox" {...p}/><span>{label}</span></label>}